---
title: "AirBNB Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(flexdashboard)
library(plotly)
```

```{r include=FALSE}
data("instacart")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
instacart %>% 
  count(aisle) %>% 
  filter(n > 10000) %>%
  mutate(
    text_label = str_c("Aisle: ", aisle, "\nCount: ", n)) %>% 
  mutate(aisle = fct_reorder(aisle, n)) %>% 
  plot_ly(x = ~aisle, y = ~n, type = "scatter", mode = "markers",
          text = ~text_label)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
instacart %>% 
  filter (product_name %in% c("Pink Lady Apples","Coffee Ice Cream")) %>%
  group_by(product_name, order_dow) %>% 
  summarize(order_hour_of_day_mean = mean(order_hour_of_day)) %>% 
  plot_ly(y = ~order_hour_of_day_mean, color = ~product_name, type = "box")
```

### Chart C

```{r}
instacart %>% 
  filter (aisle %in% c("baking ingredients","dog food care","packaged vegetables fruits")) %>% 
  group_by(aisle) %>% 
  count(product_name) %>% 
  plot_ly(x =~aisle, y = ~n, color = ~aisle, type = "bar", colors = "viridis")
```

## rmarkdown::render("dashboard.Rmd", output_format = "flexdashboard::flex_dashboard")
