---
title: "Plotly"
output: 
  html_document:
    toc: true
    toc_float: true
---

We are going to make some plotly plots. 

## Load packages and data

```{r}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

Let's get some data
```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(rating = review_scores_location / 2) %>% 
  select(
    borough = neighbourhood_group, neighbourhood, price, room_type, 
    lat, long, rating
    ) %>% 
  filter(
    borough == "Manhattan",
    room_type == "Entire home/apt",
    price %in% 100:500
    ) %>% 
  drop_na(rating)
```

Let's make a scatterplot!!

```{r}
nyc_airbnb %>% 
  mutate(
    text_label = str_c("Neighbourhood: ", neighbourhood, "\nPrice: ", price)) %>% 
  plot_ly(
    x = ~lat, y = ~long, color = ~price,
    type = "scatter", mode = "markers",
    alpha = 0.5, text = ~text_label
  )
```


Can we make boxplots?? Sure can

```{r}
nyc_airbnb %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>% 
  plot_ly(y = ~price, color = ~neighbourhood, 
         type = "box", colors = "viridis")
```

Can we make a barplot??

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>%
  plot_ly(
    x = ~neighbourhood, y = ~n,
    type = "bar"
  ) 
```


## ggplotly ...

```{r}
ggp_scatterplot = 
  nyc_airbnb %>% 
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point()

ggplotly(ggp_scatterplot)
```

## Create a dashboard...

Not here though. 









